# Generated by Django 5.0.1 on 2024-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class_id', models.IntegerField()),
                ('question', models.TextField()),
                ('question_property_id', models.IntegerField()),
                ('answer_property_id', models.IntegerField()),
            ],
        ),
    ]
