# Generated by Django 5.0.1 on 2024-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_property_id',
        ),
    ]
