# Generated by Django 5.0.1 on 2024-02-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_questionmodel_question_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answer_mode', models.CharField(max_length=100)),
            ],
        ),
    ]
