# Generated by Django 5.0.1 on 2024-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_gamemode_allow_answer_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100),
            preserve_default=False,
        ),
    ]
