# Generated by Django 5.0.1 on 2024-03-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_questioncategory_questionmodel_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.questioncategory'),
        ),
    ]
