# Generated by Django 5.0.1 on 2024-03-02 09:48

from django.db import migrations


def create_blank_category(apps, schema_editor):
    QuestionCategory = apps.get_model('apps', 'QuestionCategory')
    QuestionCategory.objects.create(name='Uncategorized')


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_questionmodel_category'),
    ]

    operations = [
        migrations.RunPython(create_blank_category)
    ]
