# Generated by Django 5.0.1 on 2024-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_create_blank_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
