# Generated by Django 5.0.1 on 2024-03-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_imagecustomquestion_textcustomquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecustomquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textcustomquestion',
            name='user',
        ),
    ]
