# Generated by Django 5.0.1 on 2024-03-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_imagecustomquestion_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecustomquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcustomquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100),
            preserve_default=False,
        ),
    ]
