# Generated by Django 5.0.1 on 2024-03-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_game_gamequestion_questionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.questionhistory'),
        ),
    ]
