# Generated by Django 5.0.1 on 2024-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_gamequestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
