# Generated by Django 5.0.1 on 2024-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_gamequestion_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rank_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rank_before',
            field=models.IntegerField(default=0),
        ),
    ]
