# Generated by Django 5.0.1 on 2024-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_game_rank_after_game_rank_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
